# Generated by Django 5.2.5 on 2025-08-11 13:34

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(choices=[('London', 'London'), ('New York', 'New York'), ('Tokyo', 'Tokyo'), ('Paris', 'Paris'), ('Karachi', 'Karachi')], max_length=100)),
                ('temperature', models.FloatField()),
                ('humidity', models.PositiveIntegerField()),
                ('conditions', models.CharField(max_length=255)),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('city', models.CharField(choices=[('London', 'London'), ('New York', 'New York'), ('Tokyo', 'Tokyo'), ('Paris', 'Paris'), ('Karachi', 'Karachi')], max_length=100)),
                ('subscribed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'unique_together': {('email', 'city')},
            },
        ),
    ]
