# Generated by Django 5.2.5 on 2025-08-11 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usersubscription',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='city',
            field=models.CharField(choices=[('London', 'London'), ('New York', 'New York'), ('Tokyo', 'Tokyo'), ('Lahore', 'Lahore'), ('Karachi', 'Karachi')], max_length=100),
        ),
        migrations.AlterField(
            model_name='weatherlog',
            name='city',
            field=models.CharField(choices=[('London', 'London'), ('New York', 'New York'), ('Tokyo', 'Tokyo'), ('Lahore', 'Lahore'), ('Karachi', 'Karachi')], max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='usersubscription',
            unique_together={('user', 'city')},
        ),
    ]
